name: betto_builder_tools
description: A small set of tools to assist with code generation.
version: 0.1.0
repository: https://github.com/bettongia/builder_tools

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  archive: ^4.0.9
  dart_style: ^3.1.9
  http: ^1.6.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
